=== huhongjun/myrmengine/RMEngine/docu/xsd/rmconfig.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema 由 XMLSpy v2006 U 创建 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="mainviews"/>
				<xs:element ref="players"/>
				<xs:element ref="editors"/>
				<xs:element ref="skins"/>
			</xs:sequence>
			<xs:attribute name="description" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="rmplayer/rmeditor共用配置文件"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="editor">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="XMLEditor"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="url" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="plugin/editor/XMLEditor.swf"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="editors">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="editor"/>
			</xs:sequence>
			<xs:attribute name="description" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="编辑器列表,用于player配置中editorurl的参考"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="mainviews">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="view" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="default" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="flex"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="description" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="rmplayer用于选择皮肤"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="player">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="FLVPlayer"/>
						<xs:enumeration value="ImagePlayer"/>
						<xs:enumeration value="QTIPlayer"/>
						<xs:enumeration value="SWFPlayer"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="url" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="plugin/player/FLVPlayer.swf"/>
						<xs:enumeration value="plugin/player/ImagePlayer.swf"/>
						<xs:enumeration value="plugin/player/QTIPlayer.swf"/>
						<xs:enumeration value="plugin/player/SWFPlayer.swf"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="editorurl" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="plugin/editor/XMLEditor.swf"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="players">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="player" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="description" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="rmplayer用于加载播放器,rmeditor用于加载编辑器"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="skin">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="osx"/>
						<xs:enumeration value="yfflexskin"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="url" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="skins">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="skin" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="description" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="用于皮肤选择css的参考"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="view">
		<xs:complexType>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="flex"/>
						<xs:enumeration value="pbank"/>
						<xs:enumeration value="picc"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="flash"/>
						<xs:enumeration value="flex"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="url" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="plugin/skin/MainFlex.swf"/>
						<xs:enumeration value="plugin/skin/PBank.swf"/>
						<xs:enumeration value="plugin/skin/PICC.swf"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="skin" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== huhongjun/myrmengine/RMEngine/Flex/rmplayer/src_flex/config.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->

<config description="rmplayer/rmeditor共用配置文件" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\GoogleHosting\myflash\branches\RMEngine\docu\xsd\rmconfig.xsd">
	<mainviews name="主界面皮肤" default="flex">
		<view name="系统默认" id="flex"  type="flex" 	url="plugin/skin/Flex/MainFlex.swf" skin="css/OSX/style.swf" />
		<view name="人保财险" id="picc" type="flash" 	url="plugin/skin/Flash/picc.swf" skin="" />
		<view name="人民银行" id="pbank" type="flash" 	url="plugin/skin/PBank.swf" skin="" />	
	</mainviews>
	<players name="插件-播放器" description="rmplayer用于加载播放器,rmeditor用于加载编辑器">
		<player name="SWFPlayer" url="plugin/player/SWFPlayer.swf" editorurl="plugin/editor/XMLEditor.swf"/>
		<player name="ImagePlayer" url="plugin/player/ImagePlayer.swf" editorurl="plugin/editor/XMLEditor.swf"/>
		<player name="FLVPlayer" url="plugin/player/FLVPlayer.swf" editorurl="plugin/editor/XMLEditor.swf"/>
		<player name="QTIPlayer" url="plugin/player/QTIPlayer.swf" editorurl="plugin/editor/XMLEditor.swf"/>
	</players>
	<editors name="插件-编辑器" description="编辑器列表,用于player配置中editorurl的参考">
		<editor name="XMLEditor" url="plugin/editor/XMLEditor.swf"/>
	</editors>
	<skins name="Flex皮肤样式" description="用于皮肤选择css的参考">
		<skin name="AeonGraphical" id="" url="css/AeonGraphical/style.swf"/>
		<skin name="DarkRoom" id="" url="css/DarkRoom/style.swf"/>
		<skin name="OSX" id="" url="css/OSX/style.swf"/>
		<skin name="Yahoo" id="" url="css/yahoo/style.swf"/>
		<skin name="custom" id="" url="css/custom/style.swf"/>
	</skins>
</config>
